FROM quay.io/fedora/fedora:rawhide AS builder
RUN \
    --mount=type=cache,dst=/var/cache/dnf,id=dnf,sharing=locked \
    dnf -y distro-sync \
    && dnf -y install fedora-packager rpmdevtools gcc bash \
    && useradd -m builder

WORKDIR /home/builder
USER builder:builder
RUN \
    rpmdev-setuptree
COPY srpms rpmbuild/SRPMS
COPY sources rpmbuild/SOURCES
COPY specs rpmbuild/SPECS
COPY append-to-rpmmacros.conf /home/builder
RUN \
    --mount=type=tmpfs,target=/tmp \
    --mount=type=secret,id=rpm_signing_key,target=/tmp/signing_body,uid=1000,gid=1000 \
    cat append-to-rpmmacros.conf >> .rpmmacros \
    && rm append-to-rpmmacros.conf \
    && echo "-----BEGIN PGP PRIVATE KEY BLOCK-----" > /tmp/signing.asc \
    && cat /tmp/signing_body >> /tmp/signing.asc \
    && echo -e "\n-----END PGP PRIVATE KEY BLOCK-----" >> /tmp/signing.asc \
    && gpg --import /tmp/signing.asc && rm /tmp/signing.asc || true
#RUN \
#    cd ~/rpmbuild/SRPMS \
#    && rpm -i *.src.rpm

USER root:root
RUN chown -R builder:builder /home/builder
RUN \
    --mount=type=cache,dst=/var/cache/dnf,id=dnf,sharing=locked \
    cd /home/builder/rpmbuild/SPECS \
    && dnf -y builddep *.spec

USER builder:builder
RUN \
    rm -rf ~/.gnupg/public-keys.d/pubring.db.lock || true \
    && cd ~/rpmbuild/SPECS \
    && echo *.spec | xargs -n 1 -P 1 -- spectool -g -R \
    && rpmbuild -ba *.spec \
    && mkdir -p /home/builder/rpmbuild/RPMS/noarch /home/builder/rpmbuild/RPMS/repo \
    && shopt -s nullglob \
    && cp -a /home/builder/rpmbuild/RPMS/x86_64/* /home/builder/rpmbuild/RPMS/noarch/* /home/builder/rpmbuild/RPMS/repo \
    && createrepo /home/builder/rpmbuild/RPMS/repo

FROM scratch AS repo
COPY --from=builder /home/builder/rpmbuild/RPMS/repo /
