FROM quay.io/fedora/fedora:rawhide as builder
RUN \
    --mount=type=cache,dst=/var/cache/dnf,id=dnf,sharing=locked \
    dnf -y install fedora-packager rpmdevtools gcc bash \
    && useradd -m builder

WORKDIR /home/builder
USER builder:builder
RUN \
    rpmdev-setuptree
COPY srpms rpmbuild/SRPMS
COPY sources rpmbuild/SOURCES
#RUN \
#    cd ~/rpmbuild/SRPMS \
#    && rpm -i *.src.rpm
COPY specs rpmbuild/SPECS
USER root:root
RUN \
    --mount=type=cache,dst=/var/cache/dnf,id=dnf,sharing=locked \
    cd /home/builder/rpmbuild/SPECS \
    && sudo dnf -y builddep *.spec

USER builder:builder
RUN \
    cd ~/rpmbuild/SPECS \
    && echo *.spec | xargs -n 1 -P 1 -- spectool -g -R \
    && rpmbuild -ba *.spec \
    && mkdir -p /home/builder/rpmbuild/RPMS/noarch /home/builder/rpmbuild/RPMS/repo \
    && cp -a /home/builder/rpmbuild/RPMS/x86_64/* /home/builder/rpmbuild/RPMS/noarch/* /home/builder/rpmbuild/RPMS/repo \
    && createrepo /home/builder/rpmbuild/RPMS/repo

FROM scratch as repo
COPY --from=builder /home/builder/rpmbuild/RPMS/repo /
