
RUN \
  --mount=type=tmpfs,target=/var \
  --mount=type=bind,from=ghcr.io/prydom/fedora-kinoite-laptop-rpms,src=/,dst=/tmp/rpms \
  echo "========== Copy RPMs ==========" \
  && cp -r /tmp/rpms/* /usr/share/local-rpm-repo \
  && echo "========== End Copy RPMs ==========" \
  && ostree container commit
