# image will be published to ghcr.io/<user>/<name>
name: fedora-kinoite-laptop
# description will be included in the image's metadata
description: Overlay for fedora-kinoite containing the personal modifications I use on my laptop.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-kinoite
image-version: rawhide

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # WORKAROUND: increment the CACHEBUST variable below to bust the docker cache
  - type: script
    snippets:
      - CACHEBUST=0; /usr/bin/true

  # copy only files needed by rpm and dracut
  - type: files
    files:
      - etc/yum.repos.d: /etc/yum.repos.d
      - etc/pki: /etc/pki
      - etc/dracut.conf.d: /etc/dracut.conf.d

  # Secure Boot and initramfs
  - type: rpm-ostree
    install:
      - sbsigntools
      - systemd-boot-unsigned
      - systemd-ukify
      - zstd

  # We use a stable kernel instead of the one from rawhide
  - type: script
    snippets:
      - rpm-ostree override replace kernel-modules-core kernel-modules-extra kernel-core kernel-modules kernel --experimental --from repo=fedora-40-kernel
      - rm -f /usr/lib/modules/*/initramfs.img
      - rmdir --ignore-fail-on-non-empty /usr/lib/modules/*
      - /tmp/config/scripts/regen-initramfs.sh

  - type: script
    snippets:
      # WORKAROUND: for packages which deploy to /opt
      # TODO: look at switching to ostree-state-overlay@opt.service
      - mv /opt /opt.orig
      - ln -s /usr/lib/opt /opt

  # CLI Utils
  - type: rpm-ostree
    install:
      - htop
      - mosh
      - ncdu
      - stow
      - tmux
      - vim
      - ydotool
      - zsh

  # Virtualization
  - type: rpm-ostree
    install:
      - guestfs-tools
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - python3-libguestfs
      - qemu-kvm
      - virt-install
      - virt-manager
      - virt-top
      - virt-viewer

  # Development
  - type: rpm-ostree
    install:
      - binutils
      - bootc
      - distrobox
      - dnf5
      - kate
      - patchelf

  # Media and RPMFusion packages
  - type: rpm-ostree
    install:
      # Media
      - libva-utils
      - mpv
      # RPMFusion
      - ffmpeg
      - ffmpeg-libs
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - mesa-va-drivers-freeworld
      - mesa-vdpau-drivers-freeworld
    remove:
      # Replace with freeworld packages from rpmfusion
      - libavfilter-free
      - libavformat-free
      - libpostproc-free
      - libswresample-free
      - libavutil-free
      - libswscale-free
      - libavcodec-free
      - mesa-va-drivers

  - type: script
    snippets:
      # WORKAROUND: Create the group for 1Password with the a consistent GID
      # Also, 1Password requires the GID to be > 1000
      - groupadd -g 5001 "onepassword"
      - groupadd -g 5002 "onepassword-cli"

  # Proprietary
  - type: rpm-ostree
    install:
      - 1password
      - 1password-cli
      - google-chrome-stable
      - tailscale

  # Do local packages as script because we can't do replace with the bluebuild module
  - type: script
    snippets:
      - rpm-ostree override replace /tmp/config/rpms/krfb-24.02.0-1.fc41_jxpryde.x86_64.rpm /tmp/config/rpms/krfb-libs-24.02.0-1.fc41_jxpryde.x86_64.rpm
      - rpm-ostree install /tmp/config/rpms/1password-ostree-workaround-0.0.0_main-1.fc41.x86_64.rpm

  # copy rest of customizations
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: systemd
    system:
      enabled:
        - systemd-timesyncd.service
        - tailscaled.service
        - tailscaled-restart.service
        - libvirtd.service
      disabled:
      masked:
      unmasked:
    user:
      enabled:
      disabled:
      masked:
      unmasked:

  - type: script
    snippets:
      - rm /opt
      - mv /opt.orig /opt

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
